---
title: "Lisbon: Jogo do Pau"
output: pdf_document
fontsize: 12pt
header-includes:
- \pagenumbering{gobble}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

Olà,

At the Lisbon offsite, in keeping with local and Smartodds traditions, you are invited to participate in a game of [\textcolor{red}{Jogo do Pau}](https://en.wikipedia.org/wiki/Jogo_do_pau), which translates roughly as ‘Game of Stick’. The origins of this game date back to medieval times, when fighting with sticks was a standard form of defence for foot soldiers who lacked the means for better weaponry. It was brought to Lisbon in the 19th century and subsequently
developed into a sporting martial art. A video illustrating the sport, which is rather like a primitive version of fencing, can be seen [\textcolor{red}{here}](https://youtu.be/CFucsRevxCw?si=j0ysud74TPq47UmY). I haven’t been able to find a list of the rules, but basically it seems like a body blow  to the opponent wins a point. 

There are [\textcolor{red}{three standard training methods}](https://stafffighters.com/blog/2017/05/10/sarilhos-formas-and-series-in-jogo-do-pau/) for Jogo do Pau: 

1. Sarilhos: Technical defense movements trained in sequence in previously determined timings and movements.
2. Formas : Multiple opponent combat simulations done through the execution of a fixed sequence of attacks and defenses.
3. Séries: These were part of the traditional training method of the old masters.

At the offsite, we will run a (simulation!) tournament to see who is the Grand Master of Jogo do Pau. The Grand Master becomes a Jogo do Pau purple belt, and may also win a prize (subject to generosity of Smartodds management.)

## Playing and Betting

There are two aspects to the tournament: playing and betting. You will play the tournament as an individual, but bet as part of a team. 
As explained below, to participate in the tournament you are required  to allocate a budget to optimise your training and general preparation for the tournament. You are provided with some historical data to help you choose how to make this allocation, and must send me your choices in advance of the meeting. At Lisbon we'll simulate the tournament  from the round-of-16 onwards. The tournament will have standard knock-out format, with matches played between pairs of players. Each match is won by the first player to reach 5 points. The probability of either player winning any point in a match will depend on the combination of spending choices made by each player. Assuming there are more than 16 participants, I'll run a pre-tournament simulation to identify the 16 tournament participants. 

Once the 16 participants have been identified, I will circulate the spending allocations they have chosen. During the Lisbon tournament, you will also be able to bet on each match. For this purpose you will be placed in teams, and may consult before the meeting to decide on your betting strategy. 

## Playing details

If you choose to participate in the tournament, you have \$15k to spend on your training which you must allocate between each of these training types, with a 
maximum spend of \$10k in each category. To help you decide how to allocate your \$15k, you are provided with data from 100 previous matches. The data include the spending allocations of each player and the match score. Note that in these matches, players were not limited to a total budget of  \$15, but could still
only spend a maximum of \$10k in each category. The data are included at the end of this note, and also attached as a csv file. Each row of the table corresponds to a single match. The first column indicates the match number.  The next 3 columns show you how much Player 1 allocated to each of the 3 categories.  Columns 5 - 7  give the equivalent information for Player 2. Each match was played until either player had scored 5 points, and the final two columns give the points score for Player 1 and Player 2 respectively. 


There are different ways of deciding how to allocate your resources. You could, simply, decide to allocate \$5k to each category. Alternatively, you could just choose values at random (subject to a maximum of \$10k in each category and a total spend of \$15k). Or you could try to use the information given in the historical data to work out what choice of resource allocation is likely to result in the best performance. 

At Lisbon we will simulate match outcomes on the basis of  each player's chosen   resource allocations. As with the historical data, 
the match winner will be the first to reach 5 points. Match winners will go through to the next round of the tournament in the usual way, right through to the final.
The tournament winner achieves the ultimate accolade of ‘purple belt’. The losing finalist becomes a ‘black belt’. There’ll be a third/fourth place playoff - third place becomes red belt, fourth place green. All other participants remain yellow belts. 

## Betting details

After the early rounds of the tournament have been simulated, just 16 players will be left for the actual tournament in Lisbon. I will circulate details of the resource allocation chosen by those players, on whom there will be a betting market during the Lisbon tournament rounds. The betting aspect of the tournament is a team competition for which the winning team will also win a prize. (Maybe.)  Teams will be allocated when the final 16 competitors are announced. The rules for the betting competition are:

\newpage

1. Each team has an initial allocation of  \$20k.

2. Bets are available on either player of each match from the round-of-16 onwards through to the final, including a 3rd/4th place play-off match,  and offered at even money. For example, if you choose to bet  \$1k on one player in a match, you win \$1k if they win, but lose \$1k if they lose.

3. Bets on all matches in a round are made at the start of that round. For example, at the start of the round-of-16, you will have the option to bet on 8 different matches, and you can choose to bet on all, some or none of them. 

4. Bets are placed in units of \$1k. 

5. There's no limit to how much you can bet on any match, subject to never going into debt. For example, at the start of the round-of-16, you can bet as much of your \$20k as you like across the 8 matches, but not exceed that amount. And if your bank ever hits zero, or you accidentally bet more than the size of your current bank, you're out.

6. The winning team will be the one with the most money after the final game is played. 


## Timeline

2 June: Deadline for sending me resource allocations for tournament play.

3 June: Results of pre-tournament simulation posted (including resource allocations chosen).

11 June: Lisbon tournament.


\newpage

## Information needed. 

To participate in the tournament, simply complete the following table and mail to me at stuart.coles1111@gmail.com. 

1. Sarilhos: 
2. Formas :
3. Séries:


The entry for each row needs to be a non-negative number less than 10,000 and the sum of the row values needs to be 15,000. For example:

1. Sarilhos: 5000
2. Formas : 5000
3. Séries: 5000


would be the table to send me if you wish to spend \$5k on each of the categories. It would be great to have as many participants as possible. I genuinely don't
know how much value is obtained by using the data to try to optimise your spending allocation, so the default choice of \$5000 per category or random selection 
may turn out to be reasonable strategies, giving you a near equal chance of winning the tournament. So, please do use either of these strategies to enter 
the tournament, even if you're not interested in analysing the data below.
