---
title: "Betting 101: A guide to betting on the Lisbon Jogo do Pau tournament"
output: pdf_document
---



## Introduction: the Lisbon Jogo do Pau tournament


As explained in my earlier note, the Jogo do Pau competition at Lisbon will include a betting market. The essential rules are:

1. You will be placed in a team for betting purposes.

2. Bets are open on each match from the round-of-16 onwards through to the final, including a 3rd/4th place decider.

3. Each team has a total of \$20k to bet with.

4. Bets on all matches are prices at evens on both players.

5. You place bets at the start of each round and can bet as much or as little on each match in that round, subject to not exceeding your current bank value at the start of that round.

6. Bets are placed in units of $1k. 

7. You will make bets privately from the other teams, but the bets placed will be displayed once all bets for a round have been confirmed. 

8. If your bank hits zero or you inadvertently bet more money than you currently possess, you are out of the competition.

9. The team with the largest bank after the final match is the winner.

## A guide to betting

In general, bets can be placed on events that might have several different outcomes and a different price -- that's to say, return -- might be offered on each of those different outcomes. The Jogo do Pau betting market is simple: you are simply betting on Player 1 or Player 2 to win. Even simpler: the amount you win if you bet on the winner is the same in each case. If you bet \$5k on Player 1 and they win, you win  \$5k; if they lose, you lose \$5k.

Generally, if you believe an event will occur with probability $p$ and the price you are offered -- including your stake -- on that event is $Q$, the bet is 'fair' if $p=1/Q$. What this means is that on average, if you made many bets of this type, you'd expect to neither win nor lose money. You might get lucky and win; you might be unlucky and lose; but on average your wins and losses will balance out. If $p<1/Q$ the bet has negative value; you'd expect, on average, to lose money.  If $p>1/Q$ the bet has positive value; you'd expect, on average, to win money.

In the case of Jogo do Pau, all of the matches have $Q=2$ for a bet on either player, so any bet has positive expected value if $p>1/2$. What this means is that if your assessment of a player is that they are likely to beat their opponent, so their win probability $p$ is bigger than 1/2, a bet on them has positive value and it's worth you making that bet. Obviously, the bigger $p$ is, the more likely they are to win, and so the more likely you are to win if you place a bet on them.

So, to decide whether to bet on a match, and who to bet on, you need a method for calculating the probability either player wins the match. Since you're in teams, you'll need to make a group decision about this. Several approaches are possible:

1. You could go on instinct, deciding which of either player in a match is the more likely to win;

2. You could try to match the spending resources of the players in the round-of-16 to those of the 100 historical matches to try to see which of the chosen combinations of spending are likely to lead to success;

3. You could try to  use the historical data to build a formal model for calculating win probabilities, given the spending allocations of either player;

4. You could try to exploit the information from the pre-round-of-16 matches to work out which players seem strongest;

5. You could use the additional information that derives from the actual tournament as it evolves.

There are obviously different levels of sophistication that can be applied, but there's also a fair amount of randomness in the match process, so it won't necessarily be that a sophisticated strategy beats a simpler one. 

There is another issue though: how many bets to place and how much to stake. There are some general theoretical strategies about staking sizes, but these are unlikely to be especially useful given the rules of this tournament, for which you have to place all of your bets at the start of each round. In the first round this means you have \$20k to potentially spend on bets on up to 8 matches. But should you risk all of it? Should you bet on all of the matches available? These are difficult decisions that are likely to be influential on determining which team wins overall. For what it's worth, I have no idea what the correct answers are to these questions, but just thinking about them is one of the points of this exercise. 

And another issue: you are not just trying to maximise your own winnings, but more importantly, trying to win more money than each of the other teams. Since you will know how much money each team has once each round has played out, you might choose to adjust your strategy on the basis of this information. For example, in the final round, if one team is a long way ahead but still catchable, you might go 'all in' to try to catch them. On the other hand, if your team is winning by a large margin, you might calculate that it's sufficient to bet conservatively. These decisions are also part of the exercise. 

And finally: the main purpose of this exercise is to have a bit of fun while also experiencing some of the issues faced by clients when having to determine their
trading strategies. If you aren't able to put much time or energy into planning your bets, just go on instinct on the day. It might just end up being the winning strategy anyway.


